train_file: ['/data1/yangzhenbang_new/blip/BLIP/annotation/coco_karpathy_train_pretrain.json',
             '/data1/yangzhenbang_new/blip/BLIP/annotation/vg_caption.json',
             ]
laion_path: ''
cc3m_path: '/data1/yangzhenbang_new/datasets/coco'

# size of vit model; base or large
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0

image_size: 224
batch_size: 32

queue_size: 57600
alpha: 0.4

# optimizer
weight_decay: 0.05
init_lr: 3e-4
min_lr: 1e-6
warmup_lr: 1e-6
lr_decay_rate: 0.9
max_epoch: 20
warmup_steps: 3000



